name: My first action
on:
  push:
    branches: [main]
    paths: [hello-world-docker-action/** ] 
  workflow_dispatch:
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
